export default {
  5.2: {
    key: "5_2",
    whatChecked: 4,
    whyChecked: 2,
    howChecked: 17,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  5.3: {
    key: "5_3",
    whatChecked: 2,
    whyChecked: 1,
    howChecked: 11,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  5.4: {
    key: "5_4",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 12,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  6.1: {
    key: "6_1",
    whatChecked: 2,
    whyChecked: 1,
    howChecked: 4,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "6.2.1.1": {
    key: "6_2_1_1",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 6,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "6.2.1.2": {
    key: "6_2_1_2",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 6,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "6.2.2.1": {
    key: "6_2_2_1",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 6,
    sources: 1,
    classification: 5,
    questions: 0,
  },
  "6.2.2.2": {
    key: "6_2_2_2",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 16,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "6.2.2.3": {
    key: "6_2_2_3",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 6,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "6.2.2.4": {
    key: "6_2_2_4",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 6,
    sources: 1,
    classification: 3,
    questions: 0,
  },
  "9.1.1.1a": {
    key: "9_1_1_1A",
    whatChecked: 3,
    whyChecked: 2,
    howChecked: 44,
    sources: 6,
    classification: 18,
    questions: 32,
  },
  "9.1.1.1b": {
    key: "9_1_1_1B",
    whatChecked: 3,
    whyChecked: 3,
    howChecked: 48,
    sources: 6,
    classification: 16,
    questions: 24,
  },
  "9.1.1.1c": {
    key: "9_1_1_1C",
    whatChecked: 2,
    whyChecked: 6,
    howChecked: 18,
    sources: 3,
    classification: 12,
    questions: 12,
  },
  "9.1.1.1d": {
    key: "9_1_1_1D",
    whatChecked: 2,
    whyChecked: 2,
    howChecked: 15,
    sources: 0,
    classification: 2,
    questions: 0,
  },
  "9.1.3.1a": {
    key: "9_1_3_1A",
    whatChecked: 1,
    whyChecked: 4,
    howChecked: 13,
    sources: 9,
    classification: 17,
    questions: 24,
  },
  "9.1.3.1b": {
    key: "9_1_3_1B",
    whatChecked: 1,
    whyChecked: 4,
    howChecked: 17,
    sources: 0,
    classification: 14,
    questions: 0,
  },
  "9.1.3.1c": {
    key: "9_1_3_1C",
    whatChecked: 1,
    whyChecked: 4,
    howChecked: 11,
    sources: 0,
    classification: 12,
    questions: 0,
  },
  "9.1.3.1d": {
    key: "9_1_3_1D",
    whatChecked: 2,
    whyChecked: 3,
    howChecked: 15,
    sources: 0,
    classification: 16,
    questions: 0,
  },
  "9.1.3.1e": {
    key: "9_1_3_1E",
    whatChecked: 1,
    whyChecked: 6,
    howChecked: 44,
    sources: 1,
    classification: 12,
    questions: 13,
  },
  "9.1.3.1f": {
    key: "9_1_3_1F",
    whatChecked: 1,
    whyChecked: 3,
    howChecked: 7,
    sources: 11,
    classification: 12,
    questions: 0,
  },
  "9.1.3.1g": {
    key: "9_1_3_1G",
    whatChecked: 1,
    howChecked: 9,
    sources: 3,
    classification: 12,
    questions: 0,
  },
  "9.1.3.1h": {
    key: "9_1_3_1H",
    whatChecked: 4,
    whyChecked: 2,
    howChecked: 23,
    sources: 2,
    classification: 16,
    questions: 0,
  },
  "9.1.3.2": {
    key: "9_1_3_2",
    whatChecked: 3,
    whyChecked: 1,
    howChecked: 17,
    sources: 1,
    classification: 16,
    questions: 0,
  },
  "9.1.3.3": {
    key: "9_1_3_3",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 8,
    sources: 3,
    classification: 12,
    questions: 0,
  },
  "9.1.3.4": {
    key: "9_1_3_4",
    whatChecked: 3,
    whyChecked: 2,
    howChecked: 9,
    sources: 1,
    classification: 11,
    questions: 0,
  },
  "9.1.3.5": {
    key: "9_1_3_5",
    whatChecked: 2,
    whyChecked: 3,
    howChecked: 9,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.1.4.1": {
    key: "9_1_4_1",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 17,
    sources: 3,
    classification: 22,
    questions: 4,
  },
  "9.1.4.2": {
    key: "9_1_4_2",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 14,
    sources: 3,
    classification: 10,
    questions: 0,
  },
  "9.1.4.3": {
    key: "9_1_4_3",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 25,
    sources: 2,
    classification: 12,
    questions: 6,
  },
  "9.1.4.4": {
    key: "9_1_4_4",
    whatChecked: 2,
    whyChecked: 1,
    howChecked: 19,
    sources: 6,
    classification: 16,
    questions: 7,
  },
  "9.1.4.5": {
    key: "9_1_4_5",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 13,
    sources: 1,
    classification: 12,
    questions: 10,
  },
  "9.1.4.10": {
    key: "9_1_4_10",
    whatChecked: 4,
    whyChecked: 3,
    howChecked: 14,
    sources: 1,
    classification: 11,
    questions: 0,
  },
  "9.1.4.11": {
    key: "9_1_4_11",
    whatChecked: 4,
    whyChecked: 1,
    howChecked: 28,
    sources: 1,
    classification: 11,
    questions: 0,
  },
  "9.1.4.12": {
    key: "9_1_4_12",
    whatChecked: 2,
    whyChecked: 1,
    howChecked: 9,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.1.4.13": {
    key: "9_1_4_13",
    whatChecked: 3,
    whyChecked: 2,
    howChecked: 13,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.2.1.1": {
    key: "9_2_1_1",
    whatChecked: 1,
    whyChecked: 3,
    howChecked: 17,
    sources: 3,
    classification: 16,
    questions: 0,
  },
  "9.2.1.2": {
    key: "9_2_1_2",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 14,
    sources: 0,
    classification: 12,
    questions: 0,
  },
  "9.2.1.4": {
    key: "9_2_1_4",
    whatChecked: 1,
    whyChecked: 1,
    howChecked: 11,
    sources: 1,
    classification: 9,
    questions: 2,
  },
  "9.2.2.1": {
    key: "9_2_2_1",
    whatChecked: 2,
    whyChecked: 3,
    howChecked: 26,
    sources: 0,
    classification: 16,
    questions: 3,
  },
  "9.2.2.2": {
    key: "9_2_2_2",
    whatChecked: 2,
    whyChecked: 6,
    howChecked: 14,
    sources: 3,
    classification: 16,
    questions: 0,
  },
  "9.2.3.1": {
    key: "9_2_3_1",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 7,
    sources: 6,
    classification: 8,
    questions: 0,
  },
  "9.2.4.1": {
    key: "9_2_4_1",
    whatChecked: 3,
    whyChecked: 5,
    howChecked: 32,
    sources: 8,
    classification: 14,
    questions: 4,
  },
  "9.2.4.2": {
    key: "9_2_4_2",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 15,
    sources: 3,
    classification: 12,
    questions: 0,
  },
  "9.2.4.3": {
    key: "9_2_4_3",
    whatChecked: 1,
    whyChecked: 6,
    howChecked: 19,
    sources: 1,
    classification: 16,
    questions: 0,
  },
  "9.2.4.4": {
    key: "9_2_4_4",
    whatChecked: 2,
    whyChecked: 4,
    howChecked: 12,
    sources: 13,
    classification: 21,
    questions: 0,
  },
  "9.2.4.5": {
    key: "9_2_4_5",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 6,
    sources: 3,
    classification: 8,
    questions: 0,
  },
  "9.2.4.6": {
    key: "9_2_4_6",
    whatChecked: 1,
    whyChecked: 2,
    howChecked: 12,
    sources: 0,
    classification: 10,
    questions: 0,
  },
  "9.2.4.7": {
    key: "9_2_4_7",
    whatChecked: 2,
    whyChecked: 1,
    howChecked: 14,
    sources: 0,
    classification: 17,
    questions: 3,
  },
  "9.2.5.1": {
    key: "9_2_5_1",
    whatChecked: 12,
    whyChecked: 1,
    howChecked: 9,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.2.5.2": {
    key: "9_2_5_2",
    whatChecked: 2,
    whyChecked: 2,
    howChecked: 12,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.2.5.3": {
    key: "9_2_5_3",
    whatChecked: 1,
    whyChecked: 3,
    howChecked: 10,
    sources: 1,
    classification: 9,
    questions: 0,
  },
  "9.2.5.4": {
    key: "9_2_5_4",
    whatChecked: 3,
    whyChecked: 2,
    howChecked: 7,
    sources: 1,
    classification: 9,
    questions: 0
  },
};
